apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: java-webapp
spec: 
  type: NodePort
  selector:
     app: java-webapp
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30036
      targetPort: 3306

