apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: java-webapp
spec:
  type: NodePort
  selector:
    app: java-webapp
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: 8080
